//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstandares3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen_Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen_Inventario()
        {
            this.ComprasDetalle = new HashSet<ComprasDetalle>();
            this.DetalleEgreso = new HashSet<DetalleEgreso>();
        }
    
        public int Id_almacen { get; set; }
        public string Almacen { get; set; }
        public int Id_inventario { get; set; }
        public string Inventario { get; set; }
        public Nullable<int> Existencia { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDetalle> ComprasDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEgreso> DetalleEgreso { get; set; }
    }
}
