//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstandares3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasDetalle
    {
        public int Id { get; set; }
        public int Id_documento { get; set; }
        public int Id_almacen { get; set; }
        public string Almacen { get; set; }
        public int Id_inventario { get; set; }
        public string Inventario { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
    
        public virtual Almacen_Inventario Almacen_Inventario { get; set; }
        public virtual Compras Compras { get; set; }
    }
}
