//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstandares3.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Kardex
    {
        public int Id_kardex { get; set; }
        public string Tipo { get; set; }
        public int Id_hojaEgreso { get; set; }
        public int Id_inventario { get; set; }
        public string Inventario { get; set; }
        public int Id_compra { get; set; }
        public int Id_almacen { get; set; }
        public string Almacen { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> CantidadNueva { get; set; }
        public Nullable<decimal> PrecioNuevo { get; set; }
        public Nullable<decimal> PrecioTotalNuevo { get; set; }
    }
}